### ISSUE TITLE
Rename foss-np.github.com foss-np.github.io

### ISSUE THREAD

**Issue by krazedkrish** [foss-np/foss-np.github.io#10]
If its ok with you guys lets rename foss-np.github.com as foss-np.github.io

Its a minor change but its a good one.

**Comment by xecutioner** [comment]
But why ?

**Comment by krazedkrish** [comment]
To make it sound simple
because the site is actually  http://foss-np.github.io/ 
but the repo is foss-np.github.com

Its not, a important, but makes things less complicated.

**Comment by ssldhl** [comment]
Renamed to foss-np.github.io for consistency
